config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :sessions

  resources :events 
  resources :attendances

  put 'event/:id/invitation', to: 'events#invitation', as: 'invitation'


  # Session Routes
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions
  
  root "events#index"

  # Attendances
  post 'new/attendance', "attendance#new"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :event, class_name: 'Event'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: 'creator_id'
  has_many :attendances, dependent: :destroy
  has_many :attendees, through: :attendances, source: :attendee

  scope :past_events, -> { where('date < ?', Date.today) }
  scope :future_events, -> { where('date >= ?', Date.today) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, class_name: 'Event', foreign_key: 'creator_id', dependent: :destroy
  has_many :attendances, foreign_key: 'attendee_id', dependent: :destroy
  has_many :attended_events, through: :attendances, source: :event
  validates :name, presence: true, length: { minimum: 4, maximum: 20 }
  EMAIL_FORMAT = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, format: { with: EMAIL_FORMAT }, uniqueness: true
  before_save { self.email = email.downcase }

  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_url, alert: 'Not authorized' if current_user.nil?
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :authorize, only: %i[new edit update]

  def new
    @events = Event.all
    @attendance = Attendance.new
  end

  def create
    @events = Event.all
    @user = current_user
    @attendance = @user.attendances.new(attendance_params)
    if @attendance.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def attendance_params
    params.require(:attendance).permit(:event_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authorize, only: %i[new edit update]
  def index
    @events = Event.all
  end

  def show
    @users = User.all
    @event = Event.find(params[:id])
    @attendance = Attendance.new
  end

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :date, :place)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by_email(params[:email])
    if user
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Logged in!'
    else
      flash.now.alert = 'Email or password is invalid'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @attendances = Attendance.all
    @events = Event.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'Thank you for signing up!'
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/create.html.erb
<h1>Attendances#create</h1>
<p>Find me in app/views/attendances/create.html.erb</p>

app/views/attendances/new.html.erb
<h1 class="d-flex justify-content-center">Create Your Attendance</h1>

<%= form_for @attendance do |f| %>
    <h3 class="field d-flex justify-content-center mt-3">Select The Event:</h3>  
    <div class="field d-flex justify-content-center mt-3"><%= f.collection_select :event_id, Event.all, :id, :title %> </div>  
    <div class="field d-flex justify-content-center mt-5"><%= f.submit %></div>
<% end %>

app/views/attendances/show.html.erb
<h1>Attendances#show</h1>
<p>Find me in app/views/attendances/show.html.erb</p>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/index.html.erb
<h1 class="d-flex justify-content-center">Events List</h1>
<h4 class="d-flex justify-content-center"><%= link_to "Create a new event.", new_event_path %></h4>

<% if @events.exists? %>
    <h4 class="d-flex justify-content-center"><%= link_to "Assist to a event", new_attendance_path %></h4>
<% end %>
    
<h3 class="d-flex justify-content-center mt-5">Past Events</h3>

<section class="d-flex justify-content-center">
   
    <% if @events.past_events.exists? %>
        <div>
            <% @events.past_events.each do |event| %>
                <div class="my-2">
                <div class="field d-flex justify-content-center"><%= link_to event.title, event_path(event) %></div>
                    <div class="field d-flex justify-content-center"><%= event.date %></div>
                    <div class="field d-flex justify-content-center"><%= event.place %></div>
                </div>
            <% end %>
        </div>
    <% else %>
        <h3>There are no past events to display</h3>
    <% end %>
</section>

<h3 class="d-flex justify-content-center mt-2">Upcoming Events</h3>

<section class="d-flex justify-content-center">
    <% if @events.future_events.exists? %>
    <div>
        <% @events.future_events.each do |event| %>
            <% if event.date >= Date.today%>
            <div class="my-2">
            <div class="field d-flex justify-content-center"><%= link_to event.title, event_path(event) %></div>
                <div class="field d-flex justify-content-center"><%= event.date %></div>
                <div class="field d-flex justify-content-center"><%= event.place %></div>
            </div>
            <% end %>
        <% end %>
    </div>
    <% else %>
        <h3>There are no upcoming events to display</h3>
    <% end %>
</section>

app/views/events/new.html.erb
<h1 class="d-flex justify-content-center">New Event page</h1>

<%= form_for @event do |f| %>
  <div class="field d-flex justify-content-center mt-3"><%= f.label :title %><br></div>
  <div class="field d-flex justify-content-center"><%= f.text_field :title %></div> 
    
  <div class="field d-flex justify-content-center mt-3"><%= f.label :description %><br></div>
  <div class="field d-flex justify-content-center"><%= f.text_area :description %></div>

  <div class="field d-flex justify-content-center mt-3"><%= f.label :date %><br></div>
  <div class="field d-flex justify-content-center"><%= f.date_select :date %></div>  


  <div class="field d-flex justify-content-center mt-3"><%= f.label :place %><br></div>
  <div class="field d-flex justify-content-center"><%= f.text_field :place %></div> 

  <div class="field d-flex justify-content-center mt-5"><%= f.submit %></div>
<% end %>

app/views/events/show.html.erb
<h1 class="d-flex justify-content-center my-5">Event Details</h1>
<h3 class="d-flex justify-content-center">Title:</h3>
<div class="field d-flex justify-content-center"><%= @event.title %></div>
<h3 class="d-flex justify-content-center">Description:</h3>
<div class="field d-flex justify-content-center description"><%= @event.description %></div>
<h3 class="d-flex justify-content-center">Date:</h3>
<div class="field d-flex justify-content-center"><%= @event.date %></div>
<h3 class="d-flex justify-content-center">Place:</h3>
<div class="field d-flex justify-content-center"><%= @event.place %></div>
<h3 class="d-flex justify-content-center">Creator:</h3>
<div class="field d-flex justify-content-center"><%= @event.creator[:name]%></div>


 
<h1 class="d-flex justify-content-center mt-4">Event Attendees</h1>


<section class="d-flex justify-content-center">
    <div>
        <% if @event.attendees.exists? %>
        <% @event.attendees.each do |attendee| %>
            <div class="my-3">
                <div class="field d-flex justify-content-center"><%= attendee.name %></div>
                <div class="field d-flex justify-content-center"><%= attendee.email %></div>
            </div>
        <% end %>
        <% else %>
            <h3>This event has no attendees</h3>
        <% end %>
    </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item mx-3">
              <% if current_user %>
                Logged in as <%= current_user.name %>.
            </li>
            <li class="nav-item mx-3"><%= link_to "Home", root_path %></li>
            <li class="nav-item mx-3"><%= link_to "Sign out", logout_path %></li>
            <li class="nav-item mx-3"><%= link_to "Your profile", user_path(current_user) %></li>
            <li class="nav-item mx-3">
              <% else %>
                <li class="nav-item mx-3"><%= link_to "Home", root_path %></li>
                <li class="nav-item mx-3"><%= link_to "Sign up", signup_path %></li>
                <li class="nav-item mx-3"><%= link_to "Log in", login_path %></li>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
    <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>

app/views/users/show.html.erb
<h1 class="d-flex justify-content-center mb-5"><%= @user.name %> Profile</h1>

<h2 class="d-flex justify-content-center">Created Events</h2>

<section class="d-flex justify-content-center">
    <% if @user.events.exists? %>
    <div>
        <% @user.events.each do |event| %>
            <div class="my-3">
                <div class="field d-flex justify-content-center"><%= link_to event.title, event_path(event) %></div>
            </div>
        <% end %>
    </div>
    <% else %>
        <h3>There are no created events</h3>
    <% end %>
</section>

<h2 class="d-flex justify-content-center mt-4">Previously Attended Events:</h2>

<section class="d-flex justify-content-center">
    <% if @attendances.where(event_id: Event.past_events).exists? %>   
    <div>
        <% @attendances.where(attendee_id: current_user).each do |attendance| %>    
            <% if attendance.event.date < Date.today %>
                <div class="my-3">
                    <div class="field d-flex justify-content-center"><%= link_to attendance.event.title, event_path(attendance.event) %></div>
                </div>
            <% end %>
        <% end %>
    </div>
    <% else %>
        <h3><%= @user.name%> has not attended yet to any event</h3>
    <% end %>
</section>

<h2 class="d-flex justify-content-center mt-4">Upcoming Events With <%= @user.name %> Assistance:</h2>

<section class="d-flex justify-content-center">
    <% if @attendances.where(event_id: Event.future_events).exists? %>   
    <div>
        <% @attendances.where(attendee_id: current_user).each do |attendance| %>    
            <% if attendance.event.date > Date.today %>
                <div class="my-3">
                    <div class="field d-flex justify-content-center"><%= link_to attendance.event.title, event_path(attendance.event) %></div>
                </div>
            <% end %>
        <% end %>
    </div>
    <% else %>
        <h3><%= @user.name%> has not attended yet to any event</h3>
    <% end %>
</section>